### ISSUE TITLE
猫ちゃうやろ

### ISSUE THREAD

**Issue by s1720292** [visaooll/asobi#2]
https://github.com/visaooll/asobi/blob/56b8a16f26f0ce7a983a9d47e21862793d9fb3c7/sample/ex#L3

犬やろ
猫とかうける

**Comment by visaooll** [comment]
いやいや猫でしょ。常識的に考えて

**Comment by s1720246-chofu** [comment]
草

**Comment by s1720292** [comment]
は？！？！？！

ありえへんｗｗｗｗｗ

**Comment by visaooll** [comment]
まぁでも犬か。。。

**Comment by s1720246-chofu** [comment]
百理ある
